# docker-compose up --build -d
version: '3.8'
services:
  main:
    build: .
    container_name: mission_divorce
    ports:
      - "916:916"
    volumes:
      - "./src:/var/www/html"
    restart: always 
    command: >
      bash -c "
      chmod -R 755 /var/www/html/uploads &&
      chmod 555 /var/www/html/uploads/.hidden && 
      chmod 444 /var/www/html/uploads/.hidden/.flag.txt &&
      chown -R www-data:www-data /var/www/html/uploads &&
      apache2-foreground"